title: Jeevan  # You can add your name here

logo: files/jeevan_patil.JPG # Use a relative path to the logo image 

description: Data science and AI in agriculture - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: patiljeevanr@gmail.com # Allow visitors to contact you
