title: Jeevan Patil
logo: files/jeevan_patil.JPG 
description: Data science and AI in agriculture - where bytes and botany blend for a better world.
show_downloads: false 
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag 
email: patiljeevanr@gmail.com
